phpmob_changmin:
    resource: "@ChangMin/Resources/config/routing/routing.yml"

phpmob_changmin_security:
    resource: "@ChangMin/Resources/config/routing/security.yml"

phpmob_core_admin:
    resource: "@PhpMobCoreBundle/Resources/config/routing/admin/main.yml"

toro_admin_register:
    resource: "@ToroRegisterBundle/Resources/config/routing/admin/main.yml"
